### ISSUE TITLE
Configuration Missing.

### ISSUE THREAD

**Issue by kschroed** [odyslam/starknet-node#4]
Trying to get a starknet node running on a RPI4 with Balena.  I configured the advanced settings and changed the REPLACE_ME field of the Ethereum HTTP URL however the logs keep showing Ethereum HTTP URL is a required parameter.

**Comment by rpogge1** [comment]
Same thing as guy above:
 starknet-pathfinder  Error: Parsing configuration
 starknet-pathfinder  
 starknet-pathfinder  Caused by:
 starknet-pathfinder      Ethereum HTTP URL is a required parameter
Service exited 'starknet-pathfinder

**Comment by rpogge1** [comment]
> Trying to get a starknet node running on a RPI4 with Balena. I configured the advanced settings and changed the REPLACE_ME field of the Ethereum HTTP URL however the logs keep showing Ethereum HTTP URL is a required parameter.

did you ever get a resolution on this?

**Comment by odyslam** [comment]
Hey @kschroed and @rpogge1 , sorry for the late response. I completely missed this one. 

It was a misconfiguration on my part in balena.yml, which is used by the deploy button to generate the default env variables. It should be `ETH_RPC_URL` and not `ETHEREUM_RPC_URL`.

I fixed it!

**Comment by kschroed** [comment]
Confirmed working now after seeing new variable ETH_RPC_URL and setting its value.  Much appreciated!

**Comment by LordAxe** [comment]
Confirmed working.
Thank you !!!!!!!!

**Comment by LordAxe** [comment]
Question: How can we display The Pathfinder Log on the HDMI output instead of just a Balena splash screen ?
